# Generated by Django 4.1 on 2023-07-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="chead01",
            field=models.CharField(default="", max_length=10000000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead02",
            field=models.CharField(default="", max_length=10000000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead11",
            field=models.CharField(default="", max_length=10000000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead12",
            field=models.CharField(default="", max_length=10000000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead21",
            field=models.CharField(default="", max_length=10000000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="chead22",
            field=models.CharField(default="", max_length=10000000),
        ),
    ]
