# Generated by Django 4.1 on 2023-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produt_name", models.CharField(max_length=30)),
                ("desc", models.CharField(max_length=300)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
