# Generated by Django 4.1 on 2023-07-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_produt_name_product_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="produt_name",
        ),
    ]
