# Generated by Django 4.1 on 2023-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_product_name_product_produt_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.CharField(max_length=1000000000),
        ),
    ]
