# Generated by Django 4.1 on 2023-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_orders_address_alter_orders_address_line_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(max_length=100000),
        ),
    ]
