# Generated by Django 4.1 on 2023-07-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_orders_items_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
