# Generated by Django 4.1 on 2023-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_orders_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="razor_pay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="razor_pay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="razor_pay_payment_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
