# Generated by Django 4.1 on 2023-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_orders_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderupdate",
            old_name="order_id",
            new_name="razor_pay_order_id",
        ),
        migrations.AlterField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
