# Generated by Django 4.1 on 2023-07-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_rename_order_id_orderupdate_razor_pay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="razor_pay_payment_id",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="razor_pay_payment_signature",
        ),
    ]
