# Generated by Django 4.1 on 2023-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_remove_orders_razor_pay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="razor_pay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="razor_pay_payment_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
